### ISSUE TITLE
Where does the config go?

### ISSUE THREAD

**Issue by gbrlsnchs** [iamcco/diagnostic-languageserver#10]
I want to use this LSP with a different LSP client than `coc.nvim`. So, where does this LSP's config file go? Would you mind documenting it in README for non`coc.nvim` users? Thanks!

**Comment by iamcco** [comment]
I only use coc.nvim so I don't know how other lsp client config, but it must have a `initializationOptions` option for per langeuage server, therefor just put the `initializationOptions` config to their `initializationOptions` option then it should work.

**Comment by gbrlsnchs** [comment]
Oh, I see. So the `config` described in README is the initialization options! Would you mind putting that golden information in README? In my case, I want to try this LSP with `vim-lsp`, and in fact it does handle initialization options, so I should be fine...

If it's indeed all about passing things as initialization options, it's all good to close this issue (still I think it's important such information to be in the README).

Thanks!

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/64399488-389f8f00-d09b-11e9-8a3f-15d2bf741265.png)

The first block in the picture is lsp client relate config. and the second block is options pass to `initializationOptions` for `diagnostic-languageserver`.  I will update the README later.

**Comment by gbrlsnchs** [comment]
No problem! I just want to confirm that everything went fine with `vim-lsp` and this LSP. Nice job! Closing...
