### ISSUE TITLE
Change severity/security

### ISSUE THREAD

**Issue by andys8** [iamcco/diagnostic-languageserver#16]
I want to show all output of a linter as warning (and not error)

```
    "write-good": {
      "command": "write-good",
      "debounce": 1000,
      "args": ["--text=%text"],
      "offsetLine": 0,
      "offsetColumn": 1,
      "sourceName": "write-good",
      "formatLines": 1,
      "severity" : "warning",
      "formatPattern": [
        "(.*)\\s+on\\s+line\\s+(\\d+)\\s+at\\s+column\\s+(\\d+)\\s*$",
        {
          "line": 2,
          "column": 3,
          "message": 1
        }
      ]
    },
```

Doesn't have the expected effect.

![image](https://user-images.githubusercontent.com/13085980/77784936-ab824e80-705b-11ea-9ed6-c40fac4dbba3.png)

`[E]` is evidence for it being an error. Is the config wrong, or is this a bug?

Same if I try to hard-code it in `formatPattern`. Is it currently supported?

Btw. the wording "security" instead of "severity" is not quite what I would expect for this option. :)

**Comment by iamcco** [comment]
There are no 'security` option, use:

``` jsonc
"securities": {
      "undefined": "warning"
}
```

**Comment by andys8** [comment]
That looks a bit hacky, but it'll do the job 😅
