### ISSUE TITLE
Support for filename in formatPattern?

### ISSUE THREAD

**Issue by fsouza** [iamcco/diagnostic-languageserver#24]
Hey there, thank you very much for this cool project!

When using with certain linters, such as mypy, the output includes other files too (because a type checker can't really check a file in isolation). For example, efm supports that via the %f pattern in the lint-formats parameter. I was wondering if you'd accept a PR that introduces something like that to diagnostic-languageserver?

Thanks!

**Comment by iamcco** [comment]
Yes, PR is welcome.

**Comment by fsouza** [comment]
Will prepare and send something over the weekend! :D

**Comment by fsouza** [comment]
Sorry, I've been counting weekends different recently :D Finally got around and opened #26.
