### ISSUE TITLE
Add an option for filename relative to workspace directory

### ISSUE THREAD

**Issue by xulongwu4** [iamcco/diagnostic-languageserver#27]
Hi, first of all let me say that I like this plugin very much. It adds a lot of flexibility to coc.nvim.

While adding some linter and formatter myself, I found some of them can take the relative file path with respect to the workspace directory. Right now this language server supports "%text", "%filename", "%file", "%filepath". Is it support to add support for file's relative path when `rootPattern` is specified? Thanks.

**Comment by iamcco** [comment]
Not support yet.

**Comment by ngmy** [comment]
I think the relative path is very useful when running linter over Docker.
I am looking forward to it.

**Comment by iamcco** [comment]
`%relativepath` is supported
