### ISSUE TITLE
Display diagnostics only for the current file

### ISSUE THREAD

**Issue by n9v9** [iamcco/diagnostic-languageserver#29]
Hey there, first of all thanks for this nice extension.
I am using it mainly for Go with golangci-lint. This linter does checks on directories and it reports all linting errors correctly. However when I have two files say A and B which both contain linting errors and I open A then I also get the errors from B displayed inside A's window:

![image](https://user-images.githubusercontent.com/21263864/91671658-f7648280-eb28-11ea-9d57-66a5d80f507a.png)

Is it possible to only display the errors for file A and when I switch to file B to then display the errors for file B?
When I use the `sourceName` property implemented in https://github.com/iamcco/diagnostic-languageserver/pull/26, I can see from which file the linting message comes, but all messages are still displayed.

Do you accept pull requests? If so then I would try to come up with a PR that filters the returned `ILinterResult[]` based on the `textDocument.uri` path only if the aforementioned `sourceName` property is given, or something like that.

Thanks!

**Comment by iamcco** [comment]
Yes, PR is welcome. It would better do not have breaking change.

**Comment by n9v9** [comment]
Okay cool, how about an optional flag like `filterCurrentFile?: bool` that uses the above mentioned method only if it is explicitly set to `true` in the configuration? This way there should be no breaking changes as it is optional and defaults to the current method.

**Comment by iamcco** [comment]
looks good to me.
