### ISSUE TITLE
How i can install this plugin by plug-install?

### ISSUE THREAD

**Issue by dementor5** [iamcco/diagnostic-languageserver#3]
Other coc plugins may be installed by vim-plug.
How can i install diagnostic-languageserver by vim-plug too?

**Comment by iamcco** [comment]
this is not a plugin for coc. it's language service.

**Comment by iamcco** [comment]
Or you can `Plug 'iamcco/diagnostic-languageserver', { 'do': 'yarn install & yarn build' } ` use the vim-plug to clone and compile it then use absolute path to setup coc.

**Comment by dementor5** [comment]
> Or you can `Plug 'iamcco/diagnostic-languageserver', { 'do': 'yarn install & yarn build' } ` use the vim-plug to clone and compile it then use absolute path to setup coc.

I have got an error:
Post-update hook for diagnostic-languageserver ... Exit status: 127

**Comment by iamcco** [comment]
remove and use `Plug 'iamcco/diagnostic-languageserver', { 'do': 'yarn install' }`

**Comment by dementor5** [comment]
Such way does not work too:)
`Command "diagnostic-languageserver" of LS "sls" not found in $PATH`

**Comment by iamcco** [comment]
> use the vim-plug to clone and compile it then use absolute path to setup coc.

use absolute path

**Comment by dementor5** [comment]
> > use the vim-plug to clone and compile it then use absolute path to setup coc.
> 
> use absolute path

Could you give me an example of a command?
coc-tsserver coc-tsserver was established at me by this command and perfectly works:
`Plug 'neoclide/coc-tsserver', {'do': 'yarn install --frozen-lockfile'}`

**Comment by iamcco** [comment]
``` jsonc
{
  "languageserver": {
    "dls": {
      "command": "diagnostic-languageserver",
      "args": ["--stdio"],
      "filetypes": [ "sh", "email" ], // filetypes that you want to enable this lsp
      "initializationOptions": {
        "linters": {
          ...
        },
        "filetypes": {
          ...
        }
      }
    }
  }
}
```
change `diagnostic-languageserver` to `path/to/diagnostic-languageserver/bin/index.js`

**Comment by iamcco** [comment]
this is not an coc extension therefor you can't install it like other coc extensions.

**Comment by iamcco** [comment]
I have send pr to fix `~/xxx` extend so you can use `~/.vim/plugged/diagnostic-languageserver/bin/index.js` to setup coc.

https://github.com/neoclide/coc.nvim/pull/684

**Comment by dementor5** [comment]
> I have send pr to fix `~/xxx` extend so you can use `~/.vim/plugged/diagnostic-languageserver/bin/index.js` to setup coc.
> 
> [neoclide/coc.nvim#684](https://github.com/neoclide/coc.nvim/pull/684)

It became so much better. thanks!  :)

**Comment by iamcco** [comment]
I have create https://github.com/iamcco/coc-diagnostic coc extension therefor you can install it like normal coc extension

**Comment by dementor5** [comment]
Great! I tried, it works! So much more conveniently.
I think, it is necessary to specify in documentation that settings by default do not work in itself and it is required to specify in a coc-settings.json something on it seems:
```
{
  "diagnostic-languageserver.filetypes": {
    "php": "phpcs"
  }
}
```
