### ISSUE TITLE
Server doesn't support textDocument/hover

### ISSUE THREAD

**Issue by yngwi** [iamcco/diagnostic-languageserver#34]
Hi,

thank you for your awesome work. I'm having the following issue: I want to work the diagnostic-language-server in combination with other language servers, for instance with the typescript-language-server. I have several hotkeys configured that trigger different functionalities, one of them is "hover" to get informations about functions/variables. If diagnosticls is activated for a file type, whenever I press the hover-hotkey, I get the correct functionality from tsserver but at the same time I get a `server doesn't support textDocument/hover` error in the command line:

![Screenshot 2020-09-23 232039](https://user-images.githubusercontent.com/963440/94070973-6add7500-fdf3-11ea-9e9a-f6207168d811.jpg)

Is there a way to handle or suppress this error? I am also using diagnostics-nvim so could I maybe add a method for the hover event that just toggles a popup with the diagnostics message?

Regards,
Daniel

**Comment by iamcco** [comment]
It's expected that not support `textDocument/hover`. It's only support diagnostic and formatter. The LSP client you used should not send `textDocument/hover` to LSP that does not support that capabilities. The LSP have send the capabilities to LSP client https://github.com/iamcco/diagnostic-languageserver/blob/master/src/index.ts#L59.

**Comment by yngwi** [comment]
Hi, thank you for your reply. I'm using the native neovim LSP client. Does what you say mean that the behavior is a problem with my configuration or maybe a bug in the nvim_lsp? I'm sorry if I'm asking something obvious, the subject is new for me.

**Comment by iamcco** [comment]
Yes, you should change LSP client or your config to not send hover request to this LSP because it doesn't support that. If you send the hover request to the LSP that error is expected.

**Comment by yngwi** [comment]
Thank you

**Comment by yngwi** [comment]
@iamcco Just FYI, this seems to be a problem with the nvim_lsp, there is currently a pull-request open: https://github.com/neovim/neovim/pull/12764
