### ISSUE TITLE
Ignore exit code option

### ISSUE THREAD

**Issue by YaBoiBurner** [iamcco/diagnostic-languageserver#40]
Some linters, such as [gitlint](https://github.com/jorisroovers/gitlint) and [rstcheck](https://github.com/myint/rstcheck), will give an exit code other than zero even when linting was successful.
To work around this, I usually have to set the command to `sh` so I can run `true` after the command, or set up a wrapper script to suppress error codes.

Having something like an `ignoreExitCode` option would work better though.

**Comment by iamcco** [comment]
It does not use the exit code for linter.
