### ISSUE TITLE
vim.lsp.buf.formatting_sync() not working

### ISSUE THREAD

**Issue by cjjlaidler** [iamcco/diagnostic-languageserver#41]
Hi, I can run the command:

`:lua vim.lsp.buf.formatting()` which works, but `:lua vim.lsp.buf.formatting_sync(nil, 1000)` or any variation of that function is not working for me. I'm using eslint/prettier with typescript. Can you please confirm this is still working or if it's something my end?

**Comment by iamcco** [comment]
I not family with the build-in LSP client. you can open the output channel to see if it send format request to the LSP.

**Comment by cjjlaidler** [comment]
Thanks @iamcco I'll look into it

**Comment by carlitux** [comment]
@cjjlaidler maybe the timeout I have to increase to 5000 and works fine

**Comment by cjjlaidler** [comment]
Thanks @carlitux I've changed my workflow to run my formatting manually since posting this, but will give that a go. I'll close this issue now @iamcco thank you
