### ISSUE TITLE
The linters take time to refresh

### ISSUE THREAD

**Issue by FardeenCodes** [iamcco/diagnostic-languageserver#46]
While using this the warning did not gone for sometime  
even i had fixed it.

**Comment by iamcco** [comment]
Do you have a way to reproduce it?

**Comment by FardeenCodes** [comment]
Sorry for the late response .
I think it is because you do not support Textdocument/change

**Comment by iamcco** [comment]
I don't know what you mean, you can see the code there https://github.com/iamcco/diagnostic-languageserver/blob/master/src/index.ts#L82

**Comment by FardeenCodes** [comment]
Sorry I was wrong I saw an old post related to this but now I saw that this feature is deprecated https://github.com/Microsoft/vscode-python/issues/313
