### ISSUE TITLE
Questions about code design

### ISSUE THREAD

**Issue by A** [iamcco/diagnostic-languageserver#47]
Guys, sorry to disturb you, but i'd like to share some of my thoughts and feedback about that project. Sorry again for not very structured feedback, but hope it might be userful: 

- [Logger stores all logged messages](https://github.com/iamcco/diagnostic-languageserver/blob/master/src/common/logger.ts#L9) during session if it's disabled, that means, memory consuming grows up in time, that might be inconvenient for large projects. I understand your intention, but performance-wise it looks like uncontrollable memory leak.
- Project will be much easier to support without rxjs, vscode lsp already implements pub/sub, and it's quite sub-optimal to build stream to pass whole document on every change. It seems possible to get rid of this abstraction and make the codebase better both in terms of redundant cyclomatic complexity and code readability for new contributors.
- It would be great to have options to configure on which event lint is triggered (onSave, onChange, etc).
- May be I misread [this code](https://github.com/iamcco/diagnostic-languageserver/blob/master/src/handles/handleDiagnostic.ts#L253), but second return never will be executed.

I can make a PR simplifies the codebase and refactors architecture, if you'll  fine with it. What do you think?

**Comment by A** [comment]
let's me play with the code first, because yesterday it was too late at night hah and i was wrong about at least logger, and then if i'll get something useful, i let you know :)

**Comment by iamcco** [comment]
Any improvement is welcome.
