### ISSUE TITLE
languagetool support in nvim 0.5

### ISSUE THREAD

**Issue by ranjithshegde** [iamcco/diagnostic-languageserver#52]
using diagnostic-languageserver on nvim 0.5 with built-in lsp

I have configured it correctly to work with markdownlint, vim-vint & write-good. I am just unable to get it working with languagetool

```
languagetool = {
                command = "languagetool",
                debounce = 200,
                args = {"-"},
                offsetLine = 0,
                offsetColumn = 0,
                sourceName = "languagetool",
                formatLines = 2,
                formatPattern = {
                    "^\\d+?\\.\\)\\s+Line\\s+(\\d+),\\s+column\\s+(\\d+),\\s+([^\\n]+)\nMessage:\\s+(.*)$",
                    {line = 1, column = 2, message = {4, 3}}
                }
            },

```
No matter what I do it does not launch. i have changed the args to %file, %text, also commented it out. Could I receive some advice on how to config this differently?

Also, whats the best way to install languagetool? I have tried installing from the arch repo. If it is to use the standalone version, or from source, I dont know how to change the above in command section. would it be "java -jar /path/to/languagetool.jar"?

**Comment by iamcco** [comment]
Maybe languagetool change the output format, so the config doesn't work. And I don't use languagetool any more, it's too slow for me. 

You can paste the output here, and that should be helpful.

> Also, whats the best way to install languagetool? I have tried installing from the arch repo. If it is to use the standalone version, or from source, I dont know how to change the above in command section. would it be "java -jar /path/to/languagetool.jar"?

Out of scope for me.

**Comment by nomasprime** [comment]
Same issue, regex looks good still:

```
43.) Line 110, column 55, Rule ID: COMMA_COMPOUND_SENTENCE_2[3] prio=-1
Message: Use a comma before ‘but’ if it connects two independent clauses (unless they are closely connected and short).
```

**Comment by nomasprime** [comment]
@iamcco this is actually working for me, filetypes was the issue. How do I enable for all filetypes, it's possible? Couldn't find in code.

**Comment by iamcco** [comment]
> @iamcco this is actually working for me, filetypes was the issue. How do I enable for all filetypes, it's possible? Couldn't find in code.

with latest version you can use `*` for all filetypes.
