### ISSUE TITLE
Option to exclude file and folders

### ISSUE THREAD

**Issue by languitar** [iamcco/diagnostic-languageserver#58]
Not really a bug, but there's no template for feature requests.

Right now, when the LSP is asked to provide diagnostics for the whole workspace, all folders seem to be considered. However, there might be folders such as `.git` or `.venv` that should not be touched by the server. Some option to exclude them would be great.

**Comment by iamcco** [comment]
`ignore` option is support now for `linter` and `formatter`. it's `string[]` same as `.gitignore` pattern.
