### ISSUE TITLE
Skip missing binaries

### ISSUE THREAD

**Issue by lithammer** [iamcco/diagnostic-languageserver#62]
**Describe the bug**

Skip formatters/linters that can't be found in `$PATH`.

**To Reproduce**

Consider this config (using coc-diagnostic):

```json
{
  "diagnostic-languageserver.formatFiletypes": {
    "python": [
      "black",
      "isort"
    ]
  }
}
```

Typically in Python you have to activate a "virtualenv" to get access to project local tooling. But since tooling varies from project to project, it's not guaranteed that both `black` and `isort` are available. For example project A might just have `black` and project B only `isort`. But formatting only works if _both_ are available.

**Expected behavior**

It would be nice if missing tools were skipped. So given the above config, if `black` is missing, it should still run `isort`.

**Desktop (please complete the following information):**
 - OS: macOS 11.5.1

**Comment by iamcco** [comment]
Should be fix now.

**Comment by lithammer** [comment]
Thank you 🥳
