### ISSUE TITLE
stdin-filename support

### ISSUE THREAD

**Issue by neculaesei** [iamcco/diagnostic-languageserver#8]
Hey,
Thanks for the great project!
Been using coc-eslint for a while, but diagnostic-languageserver + eslint_d is unbeatable.
Prettier is one of the plugins I'm using in my eslint config. It relies on filenames to decide what rules / parser it should apply. To be able to support that with diagnostic-languageserver we need to add --stdin-filename to args.
I made a quick patch for it so that it works for me here: https://github.com/neculaesei/diagnostic-languageserver/blob/master/src/common/util.ts#L40
The problem is that with my approach these arguments are added to all linters / fixers, not just eslint, and also the default is hardcoded to "untitled.js". Maybe there could be a way to template textDocument.uri and have it in the args as {filename} in coc-settings.json.
What are your thoughts on this?
I'd be happy to provide a pull request for this.

**Comment by iamcco** [comment]
PR is welcome, and it seems similar to `%text` `%file` in args and maybe `%filename` ?

**Comment by neculaesei** [comment]
Yes! That makes sense. I'll make the changes and submit a PR.
