### ISSUE TITLE
Tree-sitter highlights group in comments are overriden

### ISSUE THREAD

**Issue by EtiamNullam** [iamcco/diagnostic-languageserver#86]
**Describe the bug**
Overrides useful tree-sitter highlights group in comments like `TODO`.

**To Reproduce**

1. Open a file for which this language server is enabled.
2. Add a comment including `TODO` according to the language of the file, for `lua` that would be
```lua
-- TODO
```
3. Notice `TODO` will be highlighted in a different color for a split second.
4. Notice it will quickly change to the color of the rest of comments.
5. Move your cursor over `TODO` text.
6. Check highlight group by running `:TSHighlightCapturesUnderCursor` command.
8. Disable `diagnosticls` with `:LspStop` command, you can specify the number to be sure.
9. Notice `TODO` is highlighted correctly according to `text.todo` highlight group.

**Expected behavior**
`diagnosticls` should not replace important highlight groups provided by the `tree-sitter`.

**Screenshots**
![image](https://user-images.githubusercontent.com/10875340/211213728-6c86a03f-b244-497f-943a-55fd4b1db01b.png)
Enabled (top) vs disabled (bottom).

![image](https://user-images.githubusercontent.com/10875340/211213843-5c1dc42a-fb5b-4bed-951d-8d3689197211.png)
Tree-sitter highlight group is listed.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by iamcco** [comment]
This language server doesn't nothing with highlight.

**Comment by EtiamNullam** [comment]
So sorry. I guess I've got confused when stopping it with `:LspStop` brought back that highlight group in `lua` files, actually `sumneko_lua` is responsible for it.
