### ISSUE TITLE
How to add sourcery as linter

### ISSUE THREAD

**Issue by ysl2** [iamcco/diagnostic-languageserver#89]
I tried to add it but failed. Here is what i did:

## 1. Test case

1. Install sourcery
    ```bash
    pip install sourcery
    ```
2. Write a example file to test
    ```python
    # example.py
    
    l = []
    for _ in range(3):
        l.append(1)
    ```
3. Diagnose the file in command line
    ```bash
    sourcery review --verbose --csv --no-summary example.py
    ```
    And the output is:
    ```text
    file,line,rule,description
    example.py,1,list-comprehension,Convert for loop into list comprehension
    ```

   HINT: The "1" is the diagnostic line number. This output is csv format, the first line is the csv table head and shouldn't be regexed.
    
## 2. The diagnostic-languageserver config made by myself

```jsonc
// coc-settings.json

"diagnostic-languageserver.filetypes": {
  "python": ["sourcery"],
},
"diagnostic-languageserver.linters": {
  "sourcery": {
    "args": [
      "review",
      "--verbose",
      "--csv",
      "--no-summary",
    ],
    "command": "sourcery",
    "formatLines": 2,
    "formatPattern": [
      "^.*\\n(.*),(\\d+),(.*),(.*)$",
      {
        "line": 2,
        "message": 4,
      }
    ],
    "sourcename": "sourcery",
  }
},

```

## 3. Debug output

NOTE: Never mind the name `builtin_fn_zip.py`, the file content is almost like the `example.py`, I just provide a minimal test case here.

![image](https://github.com/iamcco/diagnostic-languageserver/assets/39717545/0a637167-4520-4fb6-8210-f909a3de5ea3)

**Comment by iamcco** [comment]
``` jsonc
  "diagnostic-languageserver.linters": {
    "sourcery": {
      "isStdout": true,
      "isStderr": true,
      "args": [
        "review",
        "--verbose",
        "--csv",
        "--no-summary",
        "%file"
      ],
      "command": "sourcery",
      "formatPattern": [
        "^[^,]*,(\\d*),([^,]*),(.*)$",
        {
          "line": 1,
          "message": ["[", 2, "]: ", 3],
        }
      ],
      "sourceName": "sourcery",
    }
  },

```

![image](https://github.com/iamcco/diagnostic-languageserver/assets/5492542/6dc7f9f7-3e2e-484d-8444-633e6daa54ba)


But the command `sourcery review --verbose --csv --no-summary example.py` is really slow and not support stdio as input.

**Comment by ysl2** [comment]
Thank you :)

**Comment by ysl2** [comment]
In fact there is an another command `sourcery lsp`, it can open a thread to listen in the file content. But I don't know how to describe it. the `sourcery lsp` command just opens a thread and seems do nothing else. The offical sourcery configuration is configured by the `languageserver` field (please see below), however I think it is a linter and should be configured in coc-diagnostics instead of language server. The offical document can be found here: https://github.com/sourcery-ai/sourcery/wiki/Vim

```json
{
    "languageserver": {
        "sourcery": {
            "command": "sourcery",
            "args": [
                "lsp"
            ],
            "filetypes": [
                "python"
            ],
            "initializationOptions": {
                "extension_version": "coc.vim",
                "editor_version": "vim"
            },
            "settings": {
                "sourcery": {
                    "metricsEnabled": true
                }
            }
        }
    }
}
```
